### ISSUE TITLE
admin not found

### ISSUE THREAD

**Issue by laffernandes** [joaofazolo/boca-docker#33]
Firstly, congratulations on the initiative. Installing BOCA was much simpler with your docker. However, the website says that the _admin_ user does not exist, while the _system_ user enters with the password _boca_. Do you have any idea what could be happening?

**Comment by rlaiola** [comment]
@laffernandes, considering you followed the instructions at https://github.com/rlaiola/boca-docker/#quick-start:
- Log in as _system_ (password: _boca_);
- Click on the `Contest` menu, then in the dropdown list select `New`;
- Fill in the form as desired and make sure you click on the `Activate` button;
- You will be redirected to the login screen. Now, try to log in as _admin_ (password: _boca_);

Hope it helps!

Cheers

**Comment by laffernandes** [comment]
Thank you!
