### ISSUE TITLE
Boca not updating Scoreboard

### ISSUE THREAD

**Issue by equetzal** [joaofazolo/boca-docker#8]
Hello, 
My first time using boca here. 
I'm trying to create a contest to test the S4RiS.php admin tool, this is to allow neoSaris (a new scoreboard revealer) to work with boca. But as I'm simulating the contest I'm able to set the problems, set the site, etc. The contests seems to work with runs, autojudges, etc. But I cannot see the scoreboard, it says that the scoreboard is empty!
I'm not sure of why is is happening as the runs and being performed successfully. The score is on level 3 so it should be displayed. 
The BOCA logs doesn't show anything special, that tells that something is going wrong with the scoreboard, but when using the misc/Transfer-Scoreboard options it says that the main site URL is invalid. I'm using the local IP (I've tried 127.0.0.1/boca, localhost/boca). 
I think that is the expected answer as the main site (1) is itself, and that main site might not be itself when running multi-site contests. So, not sure about what's happening. 

Looking at the docker logs, I can find `2023-02-04 19:23:16 [Sat Feb 04 22:23:16.416768 2023] [access_compat:error] [pid 37] [client 172.18.0.1:48364] AH01797: client denied by server configuration: /var/www/boca/favicon.ico, referer: http://localhost:8000/boca/admin/score.php`

I've already checked some [issues](https://stackoverflow.com/questions/18392741/apache2-ah01630-client-denied-by-server-configuration) around this, but it seems to be right configured.

Sorry if I'm not providing all the required information about the issue, It's my first time setting BOCA so I'm not familiar with its setup, but I can provide more information that might be required :)

**Comment by rlaiola** [comment]
@equetzal thanks for your contact. First of all, this issue does not seem related to this project itself, but to BOCA's base repository. Anyway, I think that this might solve your problem.

* Once the system is up and running, try the following commands:
```sh
# Get boca-web's CONTAINER ID
docker container ls -a
# Next, enter in the container (replace CONTAINER_ID accordingly)
docker exec -it CONTAINER_ID /bin/bash
```
* Once inside,
```sh
# Check whether the name of your contest is registered in this file
more /var/www/boca/src/private/score.sep
# If not, add a new line with its name. In order to verify the name of a contest, login as system or admin,
# and click on the 'Contest' menu. Assuming you did not change anything, the default value is 'Contest'
$ sed -i '1 i\Contest' /var/www/boca/src/private/score.sep
$ exit
```

After that, reload the score web page and you should be able to see the rankings. Hope it helps!

Cheers.

PS: Unfortunately, BOCA's base repo is not well documented and its developers have not been very responsive to issues and/or pull requests lately. Essentially, this kind of workaround we've been learning by experience.

**Comment by josimarviana** [comment]
I have the same problem. I did the steps pointed out and it still didn't work. Do you have any more suggestions?

**Comment by rlaiola** [comment]
@josimarviana actually there was a typo in the solution described above. The correct `sed` command is:

> $ sed -i '1 i\Contest 1' /var/www/boca/src/private/score.sep

The resulting file should look like this:

<img width="622" alt="Screen Shot 2023-03-09 at 21 49 32" src="https://user-images.githubusercontent.com/4059310/224194894-339209dc-a2dc-4fc7-83e3-ef74839cc47c.png">

Brief explanation: _Contest_ is the contest given name and _1_ is the site number.

Hope it works and thanks for pointing that out.

Cheers!

**Comment by josimarviana** [comment]
Yeah. Thanks a lot. It wit worked out.

**Comment by Hgto74** [comment]
Buen dia , estoy iniciando con la configuracion recomendada, pero  ninguno de los usuario de login indicados , permite el  acceso al  aplicativo Boca, (sistema - boca) (admin - boca), podrian colaborarme ? Gracias

**Comment by rlaiola** [comment]
> 
> Buen dia , estoy iniciando con la configuracion recomendada, pero ninguno de los usuario de login indicados , permite el acceso al aplicativo Boca, (sistema - boca) (admin - boca), podrian colaborarme ? Gracias

@Hgto74 podrías ser un poco más especifico? Cuales comandos hay ejecutado? 


Creo que il tuo problema beberías estar en una nova thread.

Gracias

**Comment by Hgto74** [comment]
> > Buen dia , estoy iniciando con la configuracion recomendada, pero ninguno de los usuario de login indicados , permite el acceso al aplicativo Boca, (sistema - boca) (admin - boca), podrian colaborarme ? Gracias
> 
> @Hgto74 podrías ser un poco más especifico? Cuales comandos hay ejecutado? E cuál è il output?
> 
> Creo que il tuo problema beberías estar en una nova thread.
> 
> Gracias

Buenas tardes , mi consulta corresponde a esta parte del  proceso, en  la cual  no me permite el  ingreso  con ninguno de los usuarios que se sugieren (Abra un navegador web y visite la [URL http://localhost:8000/boca](http://localhost:8000/boca). Primero, crea y activa un concurso BOCA (usuario: sistema | contraseña: boca). Luego, inicie sesión como administrador (usuario: admin | contraseña: boca) para administrar usuarios, problemas, idiomas)

**Comment by Hgto74** [comment]
> 

User does not exist or incorrect password
